//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Models.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Models.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user_default.png.
        /// </summary>
        internal static string AvatarDefault {
            get {
                return ResourceManager.GetString("AvatarDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàng Anh Quân.
        /// </summary>
        internal static string DefaultUser {
            get {
                return ResourceManager.GetString("DefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e010.
        /// </summary>
        internal static string DevMsgAddFail {
            get {
                return ResourceManager.GetString("DevMsgAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e002.
        /// </summary>
        internal static string DevMsgDatabase {
            get {
                return ResourceManager.GetString("DevMsgDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e009.
        /// </summary>
        internal static string DevMsgDeleteFail {
            get {
                return ResourceManager.GetString("DevMsgDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e004.
        /// </summary>
        internal static string DevMsgDuplicate {
            get {
                return ResourceManager.GetString("DevMsgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e001.
        /// </summary>
        internal static string DevMsgExeption {
            get {
                return ResourceManager.GetString("DevMsgExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e006.
        /// </summary>
        internal static string DevMsgLoginFail {
            get {
                return ResourceManager.GetString("DevMsgLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e005.
        /// </summary>
        internal static string DevMsgNotFoundRecordByID {
            get {
                return ResourceManager.GetString("DevMsgNotFoundRecordByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e007.
        /// </summary>
        internal static string DevMsgRenewTokenFail {
            get {
                return ResourceManager.GetString("DevMsgRenewTokenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e008.
        /// </summary>
        internal static string DevMsgUpdateFail {
            get {
                return ResourceManager.GetString("DevMsgUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e003.
        /// </summary>
        internal static string DevMsgValidate {
            get {
                return ResourceManager.GetString("DevMsgValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng liên hệ với Hoàng Anh Quân để biết thêm thông tin chi tiết lỗi..
        /// </summary>
        internal static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ với Hoàng Anh Quân.
        /// </summary>
        internal static string UserMsg {
            get {
                return ResourceManager.GetString("UserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công.
        /// </summary>
        internal static string UserMsgAddFail {
            get {
                return ResourceManager.GetString("UserMsgAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thông tin không thành công.
        /// </summary>
        internal static string UserMsgDeleteFail {
            get {
                return ResourceManager.GetString("UserMsgDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đã tồn tại!.
        /// </summary>
        internal static string UserMsgDuplicate {
            get {
                return ResourceManager.GetString("UserMsgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        internal static string UserMsgLoginFail {
            get {
                return ResourceManager.GetString("UserMsgLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu ứng với ID của bạn.
        /// </summary>
        internal static string UserMsgNotFoundRecordByID {
            get {
                return ResourceManager.GetString("UserMsgNotFoundRecordByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin không thành công.
        /// </summary>
        internal static string UserMsgUpdateFail {
            get {
                return ResourceManager.GetString("UserMsgUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ!.
        /// </summary>
        internal static string UserMsgValidate {
            get {
                return ResourceManager.GetString("UserMsgValidate", resourceCulture);
            }
        }
    }
}
